<?php

declare(strict_types=1);

namespace App;

use chillerlan\QRCode\QRCode;
use chillerlan\QRCode\QROptions;

final class QrController
{
    public function __construct(
        private readonly Config $config,
        private readonly UserDirectory $users,
        private readonly View $view,
    ) {
    }

    public function handle(string $username, string $baseUrl, string $nonce): Response
    {
        if (!$this->users->exists($username)) {
            $content = $this->view->render('error');
            $body = $this->layout('Photo Release QR', $content, $nonce);
            return new Response(404, $body, ['Content-Type' => 'text/html; charset=UTF-8']);
        }

        $target = $baseUrl . '?u=' . urlencode($username);
        $options = new QROptions([
            'outputBase64' => false,
            'svgAddXmlHeader' => false,
        ]);
        $svg = (new QRCode($options))->render($target);

        $content = $this->view->render('qr', [
            'username' => $username,
            'svg' => $svg, // trusted: generated by the QR library, not user input
        ]);

        $body = $this->layout('Photo Release QR: ' . $this->config->orgName, $content, $nonce);
        return new Response(200, $body, ['Content-Type' => 'text/html; charset=UTF-8']);
    }

    private function layout(string $title, string $content, string $nonce): string
    {
        return $this->view->render('layout', [
            'title' => $title,
            'orgName' => $this->config->orgName,
            'content' => $content,
            'nonce' => $nonce,
            'csrfToken' => null,
        ]);
    }
}
